name: Pi Github Action Trigger
run-name: Build Pi Web App Docker Images 
on: 
    push:
        branches: [ main ]
jobs:
    Pi-Github-Actions:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ github.actor }} Triggered The Pipeline."

            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set Up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log into DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PAT_TOKEN }}
            
            - name: Build and Push Web App Dockerfile
              uses: docker/build-push-action@v6
              with:
                context: ${{ github.workspace }}/src/webapp
                file: ${{ github.workspace }}/src/webapp/Dockerfile
                push: true
                tags: khutsokobela/piweb:latest
                platforms: linux/amd64,linux/arm64


            - name: Build and Push Nginx Proxy Dockerfile
              uses: docker/build-push-action@v6
              with:
                context: ${{ github.workspace }}/src/nginx-proxy
                file: ${{ github.workspace }}/src/nginx-proxy/Dockerfile
                push: true
                tags: khutsokobela/pi-reverse-proxy:latest
                platforms: linux/amd64,linux/arm64

            - name: Tailscale Authentication
              uses: tailscale/github-action@v4
              with:
                oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
                oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
                tags: tag:github-pi-action

            - name: Copy Compose file to Pi
              uses: appleboy/scp-action@v1
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                source: "src/docker-compose.yml"
                target: "~/pi-web/"

            - name: Deploy Compose file to Pi
              uses: appleboy/ssh-action@v1.0.0
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                  cd ~/pi-web/src
                  ls -la
                  docker compose -f docker-compose.yml pull
                  docker compose -f docker-compose.yml up -d
                  docker image prune -f