name: Pi Github Action Trigger
run-name: ${{ github.actor }} trying out GH Actions
on: 
    push:
        branches: [ main ]
jobs:
    Pi-Github-Actions:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set Up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log into DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PAT_TOKEN }}
            
            - name: Build and Push Web App Dockerfile
              uses: docker/build-push-action@v6
              with:
                context: ${{ github.workspace }}/src/webapp
                file: ${{ github.workspace }}/src/webapp/Dockerfile
                push: false
                tags: khutsokobela/piweb:latest

            - name: Build and Push Nginx Proxy Dockerfile
              uses: docker/build-push-action@v6
              with:
                context: ${{ github.workspace }}/src/nginx-proxy
                file: ${{ github.workspace }}/src/ginx-proxy/Dockerfile
                push: false
                tags: khutsokobela/pi-reverse-proxy:latest